spring:
  application:
    name: spring-ddd
  profiles:
    active: '@env@'
  thymeleaf:
    check-template-location: false
  security:
    ignore-paths:
      - /auth/login
      - /auth/logout
    token-only-paths:
      - /auth/codes
      - /auth/user/info
      - /sys/menu/all