spring:
  application:
    name: spring-ddd
  profiles:
    active: '@env@'
  security:
    ignore-paths:
      - /auth/login
    token-only-paths:
      - /auth/codes
      - /auth/user/info
      - /sys/menu/all