spring:
  application:
    name: spring-ddd
  profiles:
    active: '@env@'
  security:
    ignore-paths:
      - /auth/login
      - /auth/logout
    token-only-paths:
      - /auth/codes
      - /auth/user/info
      - /sys/menu/all
gg:
  jte:
    template-location: templates
    binaryStaticContent: false